### ISSUE TITLE
README for app

### ISSUE THREAD

**Issue by speric** [csean/subscription_manager#1]
Hello @csean! 👋 

I'd like to pull this app down locally and play around with it.

Could you add a `README` with instructions for setting everything up locally, and what to do once it is set up? I think it'd also be helpful to know what problems this application solves, etc.

Thanks! 👏

**Comment by csean** [comment]
Hi @speric!

Apologies for not having a detailed instruction beforehand, but please feel free to review the modified README to see if anything is missing.

Hope you have a great weekend!

**Comment by speric** [comment]
The `README` looks good, but I am having trouble getting the tests to run. I think it has to do with the credentials.

I cloned the app, then did:
```
bundle
bundle exec rake db:create db:migrate db:test:prepare seed:migrate
bundle exec rake
```
Output:
```
1) SubscriptionsController POST #create successful transaction with billing gateway creates a new Subscription
     Failure/Error: @resource = RestClient::Resource.new(creds[:url], creds[:username], creds[:password])

     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./app/services/billing_gateway_service.rb:6:in `initialize'
     # ./spec/controllers/subscriptions_controller_spec.rb:35:in `block (4 levels) in <top (required)>'
```

**Comment by csean** [comment]
Hi @speric!

It was great talking with you today. I did update the README to be more specific on the steps for the credentials file, just want to be complete :)

Thanks so much for your time! I really appreciate it!

**Comment by speric** [comment]
Thanks @csean, it was my pleasure. 🙇
